language: python
cache: pip
dist: xenial

jobs:
  include:
#########
# Style #
#########
  - stage: Style Checking
    python: '3.7'
    install:
    - pip install -r requirements.txt
    - pip install -r dev.requirements.txt
    - pip install black
    - pip install tgcli --upgrade
    script:
    - black setup.py tests/ tglogger/ -l 79
    after_success:
    - tgcli bot send -r $TELEGRAM_RECEIVER message "ðŸ¥‚ Style check passed for \`tglogger\`."
    after_failure:
    - tgcli bot send -r $TELEGRAM_RECEIVER message "âœ‚ï¸ðŸ’¥ Style checking failed for \`tglogger\`. [See](https://travis-ci.com/erayerdin/tglogger)."

##########
# Python #
##########
# 3.5 #
  - stage: Testing
    python: '3.5'
    install:
    - pip install -r requirements.txt
    - pip install -r dev.requirements.txt
    - pip install tgcli
    script:
    - pytest
    after_success:
    - tgcli bot send -r $TELEGRAM_RECEIVER message "ðŸ» \`tglogger\` works in Python 3.5."
    after_failure:
    - tgcli bot send -r $TELEGRAM_RECEIVER message "ðŸ“¦ðŸ’¥ \`tglogger\` failed in Python 3.5. [See](https://travis-ci.com/erayerdin/tglogger)."
# 3.6 #
  - stage: Testing
    python: '3.6'
    install:
    - pip install -r requirements.txt
    - pip install -r dev.requirements.txt
    - pip install tgcli
    script:
    - pytest
    after_success:
    - tgcli bot send -r $TELEGRAM_RECEIVER message "ðŸ» \`tglogger\` works in Python3.6."
    after_failure:
    - tgcli bot send -r $TELEGRAM_RECEIVER message "ðŸ“¦ðŸ’¥ \`tglogger\` failed in Python 3.6. [See](https://travis-ci.com/erayerdin/tglogger)."
# 3.7 #
  - stage: Testing
    python: '3.7'
    install:
    - pip install -r requirements.txt
    - pip install -r dev.requirements.txt
    - pip install tgcli --upgrade
    script:
    - pytest
    after_success:
    - tgcli bot send -r $TELEGRAM_RECEIVER message "ðŸ» \`tglogger\` works in Python 3.7."
    after_failure:
    - tgcli bot send -r $TELEGRAM_RECEIVER message "ðŸ“¦ðŸ’¥ \`tglogger\` failed in Python 3.7. [See](https://travis-ci.com/erayerdin/tglogger)."

##########
# Django #
##########
# 1.11 #
  - stage: Testing with Django
    python: '3.5'
    install:
    - pip install -r requirements.txt
    - pip install -r dev.requirements.txt
    - pip install tgcli "django>=1.11<2.0" --upgrade
    script:
    - pytest --ds=django_project.settings
    after_success:
    - tgcli bot send -r $TELEGRAM_RECEIVER message "ðŸ» \`tglogger\` works in Django 1.11."
    after_failure:
    - tgcli bot send -r $TELEGRAM_RECEIVER message "ðŸ“¦ðŸ’¥ \`tglogger\` failed in Django 1.11. [See](https://travis-ci.com/erayerdin/tglogger)."
# 2.0 #
  - stage: Testing with Django
    python: '3.5'
    install:
    - pip install -r requirements.txt
    - pip install -r dev.requirements.txt
    - pip install tgcli "django>=2.0<2.1" --upgrade
    script:
    - pytest --ds=django_project.settings
    after_success:
    - tgcli bot send -r $TELEGRAM_RECEIVER message "ðŸ» \`tglogger\` works in Django 2.0."
    after_failure:
    - tgcli bot send -r $TELEGRAM_RECEIVER message "ðŸ“¦ðŸ’¥ \`tglogger\` failed in Django 2.0. [See](https://travis-ci.com/erayerdin/tglogger)."
# 2.1 #
  - stage: Testing with Django
    python: '3.5'
    install:
    - pip install -r requirements.txt
    - pip install -r dev.requirements.txt
    - pip install tgcli "django>=2.1<2.2" --upgrade
    script:
    - pytest --ds=django_project.settings
    after_success:
    - tgcli bot send -r $TELEGRAM_RECEIVER message "ðŸ» \`tglogger\` works in Django 2.1."
    after_failure:
    - tgcli bot send -r $TELEGRAM_RECEIVER message "ðŸ“¦ðŸ’¥ \`tglogger\` failed in Django 2.1. [See](https://travis-ci.com/erayerdin/tglogger)."
# 2.2 #
  - stage: Testing with Django
    python: '3.5'
    install:
    - pip install -r requirements.txt
    - pip install -r dev.requirements.txt
    - pip install tgcli "django>=2.2<2.3" --upgrade
    script:
    - pytest --ds=django_project.settings
    after_success:
    - tgcli bot send -r $TELEGRAM_RECEIVER message "ðŸ» \`tglogger\` works in Django 2.2."
    after_failure:
    - tgcli bot send -r $TELEGRAM_RECEIVER message "ðŸ“¦ðŸ’¥ \`tglogger\` failed in Django 2.2. [See](https://travis-ci.com/erayerdin/tglogger)."

##############
# Deployment #
##############
  - stage: Covering / Deploy
    python: '3.7'
    install:
    - pip install -r requirements.txt
    - pip install -r dev.requirements.txt
    - pip install tgcli --upgrade
    script:
    - pytest --ds django_project.settings --cov-config .coveragerc --cov tglogger tests/
    - codecov
    after_success:
    - tgcli bot send -r $TELEGRAM_RECEIVER message "ðŸ¾ \`tglogger\` coverage has passed."
    after_failure:
    - tgcli bot send -r $TELEGRAM_RECEIVER message "âœ‚ï¸ðŸ’¥ \`tglogger\` coverage has failed. [See](https://travis-ci.com/erayerdin/tglogger)."
    before_deploy:
    - tgcli bot send -r $TELEGRAM_RECEIVER message "ðŸš¢ Deploying on PyPI..."
    deploy:
      provider: pypi
      user: erayerdin
      password:
        secure: "FUpSNv+ZAt9OgDd3XEOr0G6mQbot/Dyg2HHJ4Xi0/MksWEUurA7gUwaf2ozRdlXG7Ere27OC6/lb397ScYX8x/QgebDcVAcGlbDurox4bL29jHFnGM4k8PlG8a6Prlutknmf3kYbLRTue7m/B96sO7+ankncF3Ig4NPWf9kzEs+JXVzERwQILgPdnxYn1yeNUQszUj/iWQ5tQOxKLL3TaSVRKPOfvcg+27TaK/g7t+dXaBrLkUlyUWu7VXYvPGPXbclGZLgUuK3KmX0BrHgaAU4HOBK8npVa0yvvSXjmB2/Z3UBJFmirFqvxpDxR77Z054J/Brk/5/jP1B77pUn33E47gvli23Nuh5yxAkGBs5BK5z1VAI7nyOYsFeKcZdm5jEs+EwvX4WudhVR2LySxjTmLDiegLpGAtW2vz/zRbUUVS49gYNkNKatm5hCS/g62KDEv/ibg7GO/uvJWEU+ZdAj3Z+GNvFeX0c4RHEROfygiMVVsTzqD39tP+g2++UACKrx0smWOGnjTzHaITJxP+hSCsLgO0iE+t/yU/1BKHyUKpe0rX4f/iqigXaw0L4uf3sriW9YF0POlIdwBYIV9QAAOztBtqFVHqApUd0rVdoDWlgogGMNyDujEfnlbnBuWc6v+tw4HLkhWFmgRdBGsvL6YkYSvWqrQwG6h6cTCACE="
      on:
        tags: true
